/*
 * State Enums
 *
 */

export enum EXAMPLE_UPLOAD_STATE {
    SUCCESS = 'FILE_STATE_SUCCESS',
    UPLOADING = 'FILE_STATE_UPLOADING',
    FAILED = 'FILE_STATE_FAILED',
    WAITING = 'FILE_STATE_WAITING',
}
